### ISSUE TITLE
🐛 Bug Report: Upload returns 413 with cloudlfare tunnel

### ISSUE THREAD

**Issue by vedranius** [stonith404/pingvin-share#57] opened 2022-12-20 12:16 UTC
### 👟 Reproduction steps

When I try to upload larger file it will just stop after few seconds.
I've set the maximum upload 10GB.
I've tried to send 2.4GB file, ISO and I get the errors 403 and 413 in console.
Using chrome to upload.

### 👍 Expected behavior

Upload normally.

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/17914869/208664790-79b9b619-4eb6-42ef-8e35-b0b5cd96ba85.png)
![image](https://user-images.githubusercontent.com/17914869/208664868-c26567db-4c92-403e-a418-aba69fd772c1.png)

### 🌐 Browser

Chrome

**Comment by stonith404** [comment] 2022-12-20 13:07
Are you using cloudflare?

**Comment by vedranius** [comment] 2022-12-20 13:40
> 

Yes, forgot to mention that.

**Comment by stonith404** [comment] 2022-12-20 15:26
@vedranius Which reverse proxy do you use?

**Comment by vedranius** [comment] 2022-12-20 15:30
> @vedranius Which reverse proxy do you use?

I suppose none. I'm using a self-hosted Proxmox machine at home which is being tunneled toward the Cloudflare and that's how I'm accessing it.

**Comment by stonith404** [comment] 2022-12-20 15:42
Currently every file gets uploaded at once and Cloudlfare only [allows 100mb per request](https://community.cloudflare.com/t/413-request-entity-too-large-problem/280057). You would have to disable the tunnel for Pingvin Share. There is an active issue about this problem #42

**Comment by vedranius** [comment] 2022-12-20 15:47
> Currently every file gets uploaded at once and Cloudlfare only [allows 100mb per request](https://community.cloudflare.com/t/413-request-entity-too-large-problem/280057). You would have to disable the tunnel for Pingvin Share. There is an active issue about this problem #42

Oh, I didn't know that free Cloudflare is limited to only 100mb per request. 
Thanks for explaining that.
So, the only way right now is to create a compressed split files. Which for my purpose is also fine.

**Comment by stonith404** [comment] 2022-12-20 15:56
Yeah at the moment it's really difficult with Cloudflare. It has a big priority to implement chunked uploads (split the files automatically), but this will also take much work to implement. As a workaround you could also disable the tunnel on Cloudflare, if you don't care that your machine is exposed to the internet directly

**Comment by vedranius** [comment] 2022-12-20 16:07
> Yeah at the moment it's really difficult with Cloudflare. It has a big priority to implement chunked uploads (split the files automatically), but this will also take much work to implement. As a workaround you could also disable the tunnel on Cloudflare, if you don't care that your machine is exposed to the internet directly

Yes, that would be an option. But then I can't access the Pingvin Share from outside of my network... And I can't share files with anyone else?

**Comment by stonith404** [comment] 2022-12-20 16:59
Can't you disable the proxy like this? 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/58886915/208723267-b39de2ae-fae6-438f-b081-5e225ba59527.png">

**Comment by vedranius** [comment] 2022-12-20 17:29
> Can't you disable the proxy like this? <img alt="image" width="1012" src="https://user-images.githubusercontent.com/58886915/208723267-b39de2ae-fae6-438f-b081-5e225ba59527.png">

Sadly that doesn't work for me when I turn off the proxy.
For some reason then Pingvin starts to act weird. I can't log in one one PC, on another I'm logged it but I can't upload a file... 

Can you maybe share how did you set it up on your side? Tunneling?
Tnx!

**Comment by stonith404** [comment] 2022-12-21 12:18
@vedranius Maybe I've understood your setup incorrectly. I'm not using the cloudflare tunnel. I just forward my Raspberry Pi port the the internet and I set an A record on cloudflare to my home address. On cloudlfare you can enable or disable if there should be a proxy between the client and the target ip (home ip).

**Comment by anthonyrussano** [comment] 2022-12-29 18:06
I was planning to use Cloudflare tunnel with a very similar setup to vedranius... however would this also affect the ability to download files larger than 100mb

**Comment by stonith404** [comment] 2023-01-09 11:17
Should be fixed now with `v0.6.0` and chunk uploads. Feel free to reopen the issue if it still occurs.

**Closed by stonith404** 2023-01-09 11:17 UTC
Labels: bug

**Comment by vedranius** [comment] 2023-01-09 16:45
> Should be fixed now with `v0.6.0` and chunk uploads. Feel free to reopen the issue if it still occurs.

I've tested it now through cloudflare and it works fine.
But it seems that I can't download it when I share the external URL.

I get this in inspect console:
![image](https://user-images.githubusercontent.com/17914869/211361659-3515228c-13be-4438-af22-12c5c6d232e4.png)

**Comment by stonith404** [comment] 2023-01-09 17:06
@vedranius That is strange I can't reproduce it on Chrome or with the Pingvin Share PWA on Chrome. What exactly is the issue, does nothing happen when you click on the download button?

**Comment by vedranius** [comment] 2023-01-09 22:20
> @vedranius That is strange I can't reproduce it on Chrome or with the Pingvin Share PWA on Chrome. What exactly is the issue, does nothing happen when you click on the download button?

Yes, nothing happens. It doesn't start download, clicking on a download doesn't seem to trigger anything for me in a Chrome...

**Comment by stonith404** [comment] 2023-01-10 22:36
@vedranius I try to reproduce this issue, but I can't. Just to be sure, with Chrome extension you probably mean the Pingvin Share PWA (Progressive Web App)? The only thing that looks wrong are the requests on the screenshot that return the status code 308. Could you share the response headers and body of the request that returns the status code 308?

**Comment by vedranius** [comment] 2023-01-11 10:31
> @vedranius I try to reproduce this issue, but I can't. Just to be sure, with Chrome extension you probably mean the Pingvin Share PWA (Progressive Web App)? The only thing that looks wrong are the requests on the screenshot that return the status code 308. Could you share the response headers and body of the request that returns the status code 308?

I get:
`Mixed Content: The site at 'https://pingvinshare.myaddres.com' was loaded over a secure connection, but the file at 'http://pingvinshare.myaddres.com/api/shares/Q2MzQ2N/files/0ee87e7d-6b03-426a-a25a-ec45ca2e4d75?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaGFyZUlkIjoiUTJNelEyTiIsImZpbGVJZCI6IjBlZTg3ZTdkLTZiMDMtNDI2YS1hMjVhLWVjNDVjYTJlNGQ3NSIsImlhdCI6MTY3MzQzMjYzNCwiZXhwIjoxNjczNDMzMjM0fQ.1gZW16wqfCI6MkvsYcy1Ekp7OqIElOR8C9BzDAd5_lk' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.`

But when I change it on CloudFlare to HTTPS then I can't access it anymore and I get this page:
![image](https://user-images.githubusercontent.com/17914869/211783577-1d55a7a6-8b37-43c2-89de-da87123b788b.png)

**Comment by vedranius** [comment] 2023-01-11 10:38
Problem is that generated share URL is https:// but should be http://
And I've set it here:
![image](https://user-images.githubusercontent.com/17914869/211784847-6054057f-cda6-4848-aa8b-c01faf3df9f2.png)
![image](https://user-images.githubusercontent.com/17914869/211785007-c539a0a4-45b2-41a5-8df9-12d3808b68fb.png)

**Comment by stonith404** [comment] 2023-01-11 12:01
Ah okay I see, this is related to #78, I fix this ASAP. So you're using Pingvin Share with http, aren't you?

**Comment by stonith404** [comment] 2023-01-11 12:10
Could you try if the error still occurs in `v0.6.1`?

**Comment by vedranius** [comment] 2023-01-11 12:22
> Could you try if the error still occurs in `v0.6.1`?

I've recreated the Portainer image of PingvinShare and selected "Pull latest".
So is that the version v0.6.1? And how to check if it is?


> Ah okay I see, this is related to #78, I fix this ASAP. So you're using Pingvin Share with http, aren't you?

Yes, I'm using it now in http as I didn't set https.

**Comment by stonith404** [comment] 2023-01-11 12:28
@vedranius The build usually takes an hour, so the new image is not available yet, you can check the status [here](https://github.com/stonith404/pingvin-share/actions/runs/3892644276). You can check the version on the admin page at the bottom.
