### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by sahara101** [stonith404/pingvin-share#261] opened 2023-09-21 18:20 UTC
### 👟 Reproduction steps

Start the container

### 👍 Expected behavior

Running

### 👎 Actual Behavior

Listening on port 3000 url: http://0.0.0.0:3000
Environment variables loaded from prisma/.env
Running seed command `ts-node prisma/seed/config.seed.ts` ...
PrismaClientUnknownRequestError: 
Invalid `prisma.config.update()` invocation in
/opt/app/backend/prisma/seed/config.seed.ts:198:27
  195     value: existingConfigVariable.value,
  196   }) != JSON.stringify(existingConfigVariable)

{
→ 198   await prisma.config.update(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))), transient: false })
    at zr.handleRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:8480)
    at zr.handleAndLogRequestError (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/opt/app/backend/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async migrateConfigVariables (/opt/app/backend/prisma/seed/config.seed.ts:198:7) {
  clientVersion: '5.0.0'
}
An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed/config.seed.ts
> pingvin-share-backend@0.18.0 prod
> prisma migrate deploy && prisma db seed && node dist/src/main
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
16 migrations found in prisma/migrations
No pending migrations to apply.
Listening on port 3000 url: http://0.0.0.0:3000

### 🌐 Browser

Safari

**Comment by stonith404** [comment] 2023-09-21 18:22
Duplicate of #260. Please search for similar issues before your create an issue.

Please see the[ note in the release notes](https://github.com/stonith404/pingvin-share/releases/tag/v0.18.0):

> ⚠️ Warning
As the Docker image doesn't use the root user anymore, you might change the data directory permissions.
This can be done with sudo chown -R your-user data

**Closed by stonith404** 2023-09-21 18:22 UTC
Labels: bug
