### ISSUE TITLE
🐛 Bug Report: Invalid access_token

### ISSUE THREAD

**Issue by maurxce** [stonith404/pingvin-share#308] opened 2023-11-01 17:07 UTC
### 👟 Reproduction steps

- Visit Pingvin Share
- Use navigation

### 👍 Expected behavior

- Navigation works

### 👎 Actual Behavior

- It doesn't sometimes

It worked fine before the app crashed because of the file upload, after that it kinda stopped working. I have to switch over to Edge to be able to use it.

### 🌐 Browser

Chrome Version 118.0.5993.118 (Official Build) (64-bit)

**Comment by maurxce** [comment] 2023-11-01 17:42
It seems to be related to the `/upload` endpoint

**Comment by maurxce** [comment] 2023-11-01 17:47
Deleting the `access_token` cookie fixed this issue for me

**Comment by zz5840** [comment] 2023-11-03 07:32
This may occur after restarting docker container, did you install the app with docker?

**Comment by maurxce** [comment] 2023-11-03 07:33
> This may occur after restarting docker container, did you install the app with docker?

Yes I deployed this using docker, I did not restart the container however, I just reopened the web page

**Comment by zz5840** [comment] 2023-11-03 07:36
Maybe the docker container auto restarted after crash. It's hard to reproduce and locate in development environment, I'll try to fix it.

**Comment by maurxce** [comment] 2023-11-03 07:40
> Maybe the docker container auto restarted after crash.

True, I haven't thought about that, that could very well be the case.
I'll see if I'm able to replicate this again once I'm home

**Comment by stonith404** [comment] 2023-11-03 07:44
@zz5840 The backend validates the JWT by verifying that it is signed correctly, the `sub` id exists in the db and if it isn't expired. 

The frontend only checks if the JWT is not expired. So the bug occurs if the frontend sees the JWT as correct but the backend not. Either the secret has changed or the user was deleted. The secret changes if you reset the database. 

@maurxce Could it be that you've made a reinstallation of Pingvin Share after you've signed in in the browser?

**Comment by zz5840** [comment] 2023-11-03 07:58
@stonith404 Just running `docker compose restart` results in this error.

Removing access token works because app will use refresh token to get a new access token.

I think we can add some mechanism to avoid this.

**Comment by stonith404** [comment] 2023-11-03 08:14
@zz5840 I think the issue is in the config seed but I currently don't have the time to test it. 

The default value of the JWT secret gets set [here](https://github.com/stonith404/pingvin-share/blob/main/backend/prisma/seed/config.seed.ts#L8)

[If the default value changes](https://github.com/stonith404/pingvin-share/blob/main/backend/prisma/seed/config.seed.ts#L278) (which happens if you restart the container as `crypto.randomBytes(256).toString("base64")` gets called again), the default value also gets updated in the db. This results in another JWT secret if you restart the container.

**Comment by zz5840** [comment] 2023-11-03 08:17
@stonith404 I see, restarting docker image makes seed script generate a new jwt token.

Should we modify the seed script or request a new access token if error occurs?

**Comment by stonith404** [comment] 2023-11-03 08:19
@zz5840 I would modify the seed script so that the JWT secret stays the same if you restart the container. I mean the secret doesn't need to be changed, right?

**Comment by zz5840** [comment] 2023-11-03 08:26
@stonith404 Yes! Thanks for fixing it! :)

**Comment by stonith404** [comment] 2023-11-03 13:09
Should be fixed in version `0.19.2`. Please let me know if it works :)

**Comment by zz5840** [comment] 2023-11-03 16:04
@stonith404 It works now, thx!

**Closed** 2023-11-03 16:05 UTC
Labels: bug
