### ISSUE TITLE
🐛 Bug Report: If you previously saved a login/password in Firefox, it fills the recipient and password fields with these credentials

### ISSUE THREAD

**Issue by mossroy** [stonith404/pingvin-share#590] opened 2024-09-08 15:26 UTC
### 👟 Reproduction steps

- Create an account on pingvin-share, and ask your browser to save the login/password
- Choose a file to share
- Click on share button
- The browser has populated recipient email field with your previously saved login, and password field with your previously saved password
- If you remove the email to set another one, Firefox adds a popover below it to suggest to use a saved login. This mostly hides the field that allows to add the e-mail address
![image](https://github.com/user-attachments/assets/21bc6426-5eb0-4823-a8dd-3eb3fc579ee6)

### 👍 Expected behavior

You should be able to upload a file without any password, even if you saved a login/password for this pingvin-share instance. And without having to manaually remove the password

### 👎 Actual Behavior

For some reason, Firefox considers that the couple "email recipients"/"share password" should be filled with saved credentials. Hopefully there is a way to avoid that, with changes in the HTML content

NB: it's a follow-up of #367

**Comment by dnielso5** [comment] 2024-09-09 22:11
I started this a while ago but didn't have time to follow up with it. #509

**Comment by alexlehm** [comment] 2024-09-22 10:12
I noticed that as well, this is likely related to naming of the forms

**Comment by stonith404** [comment] 2024-09-22 20:20
Would you mind to test the `stonith404/pingvin-share:development` image and let me know if this is fixed?

**Comment by alexlehm** [comment] 2024-09-22 22:30
the behaviour is the same as before

![image](https://github.com/user-attachments/assets/914de328-461b-4ba4-9e7b-84010f65afe5)

**Comment by mossroy** [comment] 2024-09-23 06:37
I confirm, same behavior for me too with `stonith404/pingvin-share:development` image

**Comment by alexlehm** [comment] 2024-09-23 08:02
This leads to shares that are password protected accidentally in some cases where the password is the saved pw from the logged-in user

**Comment by stonith404** [comment] 2024-09-23 08:24
Thanks for testing. Maybe the issue is caused by the password input that is in the same form. I have added `autoComplete="new-password"` to this input. Would you mind to try again by pulling the development image again?

**Comment by mossroy** [comment] 2024-09-23 08:56
The latest development image is working for me! In the sense that Firefox does not fill the wrong fields any more.

It still fills my credentials in the login form, which is what is expected. But not in other fields (e-mail recipient and password)

Many thanks

**Comment by mossroy** [comment] 2024-09-23 08:58
Don't hesitate to ask for more testing if you need to figure out if it comes from distinct forms or `autoComplete="new-password"`

**Comment by alexlehm** [comment] 2024-09-23 21:30
i can confirm that the username/account is not inserted in the share dialogue

**Comment by stonith404** [comment] 2024-09-24 10:25
Thanks for the testing. The is fixed in the latest release.

**Closed by stonith404** 2024-09-24 10:25 UTC
Labels: bug
