### ISSUE TITLE
Customizable Mail Notification

### ISSUE THREAD

**Issue by mztiq** [stonith404/pingvin-share#46] opened 2022-12-12 09:21 UTC
Hey,

really love pingvin and the feature to send mail notifications for shares.  
Any chance we could define that notification message ourselves in a text box or something?

**Comment by stonith404** [comment] 2022-12-12 12:56
Good idea👍 This feature is not on the top of priority list, but will get implemented.

**Comment by stonith404** [comment] 2022-12-15 20:45
Added in 0616a68bd2e0c9cb559ebdf294e353dd3f69c9a5 :) This allows you to set the mail message in the config section. This will get released in the next release.

**Comment by mztiq** [comment] 2022-12-15 21:02
Wow, that was pretty quick for "not on top of the priority list". Thank you very much 😊.

**Comment by mztiq** [comment] 2022-12-23 09:00
Sorry for the late reply, I just had time to test this feature (which works great btw) but I noticed that it would be quite handy to be able to customize the subject of the mail notification too.  
In my case all of my users are German and some don't speak English very well so right now I'd have a mix of English subject and German mail content.  Any chance of getting a customizable subject too and if so should I create a new issue for that?

**Comment by stonith404** [comment] 2022-12-23 10:04
Ah yeah sure, completely forgot that. I've added another config variable cabaee588b50877872d210c870bfb9c95b541921. I don't release this at the moment because the config table gets now really messy with so many configuration options. I'll officially release this when I've optimized the config page #60 .

But I've made a Docker image for you where I already added the subject config variable: `stonith404/pingvin-share:pre-release`

**Comment by mztiq** [comment] 2022-12-23 12:46
Nice, thank you very much!

**Comment by stonith404** [comment] 2022-12-30 13:43
Added in v0.5.0 :)

**Closed by stonith404** 2022-12-30 13:43 UTC
Labels: feature, waiting-for-release

**Comment by mztiq** [comment] 2022-12-30 13:55
Are you sure it's added in v0.5.0?  

It looked like this with the `stonith404/pingvin-share:pre-release`:  
![grafik](https://user-images.githubusercontent.com/92191413/210077656-2ba1ed56-de26-4be3-a462-a495d66f702f.png)

And this is from v.0.5.0, the `EMAIL_SUBJECT` option is missing for me:
![grafik](https://user-images.githubusercontent.com/92191413/210077534-352b9ed6-8030-4c86-8dbf-14a91fc043d6.png)

**Comment by stonith404** [comment] 2022-12-30 15:25
Yeah but the problem is that for some reason the build pipeline takes 1 hour. Could you try to pull again?

**Comment by mztiq** [comment] 2022-12-30 20:19
Just pulled again, the `EMAIL_SUBJECT` option is there now.
Thanks.

**Comment by stonith404** [comment] 2023-02-01 22:26
@Hukuma1 In case of the name in the email, I've just created an issue that would implement this (#93). 
Could you create a separate issue for the extension of the email message variables?
