### ISSUE TITLE
🚀 Feature: Edit expiry of existing active shares

### ISSUE THREAD

**Issue by systemcrash** [stonith404/pingvin-share#604] opened 2024-09-20 19:34 UTC
### 🔖 Feature description

Ability to change expiry date/time

### 🎤 Pitch

Current shares expire as originally intended, or the user makes a new one with different validity. Editing existing one would help.

**Comment by stonith404** [comment] 2024-09-26 13:54
Duplicate of #251. Feel free to participate in the discussion there.

**Closed by stonith404** 2024-09-26 13:54 UTC
Labels: feature
