### ISSUE TITLE
🚀 Feature: Different Maximum Size for guest and logged in users

### ISSUE THREAD

**Issue by ClassmateShen** [stonith404/pingvin-share#488] opened 2024-05-29 13:44 UTC
### 🔖 Feature description

Different Maximum Size for guest and logged in users

### 🎤 Pitch

I need to enable the visitor upload function to make it convenient to use and ensure it is not abused, but at the same time, I also have a need to share large files with others.

**Comment by gergepalfi** [comment] 2024-06-01 10:30
If I might add to this, I was about to create a separate issue for expiration as well. It would be nice if the maximum expiration and file-size could be different. I just tested setting the max expiration time, and shares that already exist keep the "never expire" date, but the admin account can't create any new ones. Administrator should always have the right to do so. The only workaround is to change the expiration or size limit, create the share and change the settings back.

Please consider adding separate settings for:
- guests
- logged in users
- administrator(s) should not be limited

**Comment by stonith404** [comment] 2024-06-10 09:22
This is a duplicate of #75, feel free to participate in the discussion there.

**Closed by stonith404** 2024-06-10 09:22 UTC
Labels: feature
