### ISSUE TITLE
🐛 Bug Report: can't upload with a low bandwidth

### ISSUE THREAD

**Issue by mossroy** [stonith404/pingvin-share#647] opened 2024-10-16 16:10 UTC
### 👟 Reproduction steps

It has been reported to me by users of a low-bandwidth ADSL line, while they succeeded with a Lufi instance.
Tested with version 1.2.0 of pingvin-share

- To simulate a very low bandwidth, you can use the dev tools of your browser. On Firefox, I reproduced with the "GPRS" profile. On Chromium/Chrome, I also reproduced with an upload speed restriction of 50kbps
- Try to upload a file of at least a few Megabytes (I tested with 8 MB)

### 👍 Expected behavior

The upload should take long, but succeed

### 👎 Actual Behavior

After exactly one minute, an error message is displayed on the user screen (in French in this example):

> Erreur
> 1 fichier(s) n’a(ont) pas pu être envoyé(s). Veuillez réessayer.

![image](https://github.com/user-attachments/assets/f2d710e8-a16d-4547-a32f-18e77d697b1d)

### 📜 Logs

On server side, the following error message is displayed:
```
[Nest] 48  - 10/15/2024, 1:36:41 PM   ERROR [ExceptionsHandler] request aborted

BadRequestError: request aborted
    at IncomingMessage.onAborted (/opt/app/backend/node_modules/raw-body/index.js:245:10)
    at IncomingMessage.emit (node:events:519:28)
    at IncomingMessage._destroy (node:_http_incoming:221:10)
    at _destroy (node:internal/streams/destroy:121:10)
    at IncomingMessage.destroy (node:internal/streams/destroy:83:5)
    at abortIncoming (node:_http_server:796:9)
    at socketOnClose (node:_http_server:790:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12) 
```

**Comment by stonith404** [comment] 2024-10-23 12:03
I can't reproduce this issue with a throttling of GPRS in Firefox on MacOS. Can you share more information about the device you are using?

**Comment by mossroy** [comment] 2024-10-23 13:55
It had been reported by a user of Firefox on latest Ubuntu 22.04, and I reproduced it with throttling of Firefox on latest Ubuntu 24.04

**Comment by stonith404** [comment] 2024-10-23 14:11
![Screenshot 2024-10-23 at 16 10 36](https://github.com/user-attachments/assets/f8e91410-8310-4657-ba4b-b47a829c265e)

Strange, I still can't reproduce this. Did you try it on another device and in another network?

**Comment by mossroy** [comment] 2024-10-23 14:52
I just reproduced it on another Ubuntu 24.04 computer (and through another network), with Firefox and GPRS throttling, on my pingvin-share instance.
However, I could not reproduce it on https://pingvin-share.dev.eliasschneider.com/

In fact, I suspect it is related to my instance (running v1.2.2 currently). It might be because it's behind a Traefik reverse-proxy, that has some timeouts (see default value of 60s for transport.respondingTimeouts.readTimeout in https://doc.traefik.io/traefik/routing/entrypoints/#transport).
I'll try to increase that (tomorrow), to see if it can be a workaround.

**Comment by mossroy** [comment] 2024-10-24 09:40
Increasing (or disabling) `transport.respondingTimeouts.readTimeout` of Treafik is a working workaround
However, this setting is for the whole Traefik instance (not only for pingvin-share), which is not ideal.

I suppose that, in my case, the transfer of a chunk (that seems to have a size of 10 MB) exceeds the default 60s timeout of Traefik.
Maybe another solution would be to have smaller chunks? Is it configurable?

**Comment by stonith404** [comment] 2024-10-24 15:49
Okay thanks for the feedback. I find it a bit strange that it is only possible to set the timeout globally but I'm not using Traefik so I can't really help you with that.

Yes, the chunk size can be changed in the admin settings, but only globally.

**Comment by mossroy** [comment] 2024-10-24 19:41
> Yes, the chunk size can be changed in the admin settings, but only globally.

Thanks, I'll try that next week with chunks of 5MB (I've removed the workaround on Traefik for now)

**Comment by stonith404** [comment] 2024-10-24 20:02
Okay. I'll close this issue as it isn't related to Pingvin Share. But feel free to still comment in this issue if you have things to share.

**Closed** 2024-10-24 20:03 UTC
Labels: bug

**Comment by mossroy** [comment] 2024-10-27 16:09
I've needed to change the chunks size to 1MB to workaround the issue with users with a slow ADSL bandwidth (after testing 5MB and 2MB)
