### ISSUE TITLE
🐛 Bug Report: pingvin unable to download files bigger than 800mb and download fails.

### ISSUE THREAD

**Issue by sebasdt** [stonith404/pingvin-share#368] opened 2024-01-01 13:08 UTC
### 👟 Reproduction steps

Not sure as I was uploading 60GB worth of games overnight for a LAN party.

But here is what I know from the logs and metrics:
- start the penguin container without ClamAV and proxy the container through.
- Upload 10 or more big files (2 GB up to 10 GB in file size)
- The container crashed due to not having enough resources (CPU, RAM)
- Hypervisor detected a vm crash, restarted it and the upload continued.
- I woke up to a completed upload to the site.
- tried to download some files to see what would happen, and here are we now.

I also noticed that the upload speeds are pretty slow. around 2mb/s and download not faster than 1mb/s. Keep in mind the pingvin server is local and should be able to reach speeds around 1gb/s

**System specs:**
- Ram: 20 GB
- Cpu: 4VCpu's (2 cores 2 threads) 
- disk space: 200GB NVME SDD
- default nginx and docker-compose config. 

### 👍 Expected behavior

Well, be able to download all files independently or as a big zip.

### 👎 Actual Behavior

When trying to download files bigger than 500mb the download failes and trows this error inside docker logs.
``` txt
docker compose logs

pingvin  |
pingvin  | > pingvin-share-backend@0.21.2 prod
pingvin  | > prisma migrate deploy && prisma db seed && node dist/src/main
pingvin  |
pingvin  |   ▲ Next.js 13.5.6
pingvin  |   - Local:        http://localhost:3333
pingvin  |   - Network:      http://0.0.0.0:3333
pingvin  |
pingvin  |  ✓ Ready in 321ms
pingvin  | Environment variables loaded from prisma/.env
pingvin  | Prisma schema loaded from prisma/schema.prisma
pingvin  | Datasource "db": SQLite database "pingvin-share.db" at "file:../data/pingvin-share.db"
pingvin  |
pingvin  | 17 migrations found in prisma/migrations
pingvin  |
pingvin  |
pingvin  | No pending migrations to apply.
pingvin  | Environment variables loaded from prisma/.env
pingvin  | Running seed command `ts-node prisma/seed/config.seed.ts` ...
pingvin  |
pingvin  | 🌱  The seed command has been executed.
pingvin  | ┌─────────────────────────────────────────────────────────┐
pingvin  | │  Update available 5.0.0 -> 5.7.1                        │
pingvin  | │  Run the following to update                            │
pingvin  | │    npm i --save-dev prisma@latest                       │
pingvin  | │    npm i @prisma/client@latest                          │
pingvin  | └─────────────────────────────────────────────────────────┘
pingvin  | [Nest] 33  - 01/01/2024, 12:16:47 PM     LOG [NestFactory] Starting Nest application...
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +26ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] JwtModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
pingvin  | Connected to the database
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] EmailModule dependencies initialized +14ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ClamScanModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] JobsModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] FileModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ReverseShareModule dependencies initialized +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] ShareModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [InstanceLoader] OAuthModule dependencies initialized +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] AppController {/api}: +16ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/health, GET} route +2ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] AuthController {/api/auth}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/signUp, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/signIn, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/signIn/totp, POST} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/resetPassword/:email, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/resetPassword, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/password, PATCH} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/token, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/signOut, POST} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/enable, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/verify, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/auth/totp/disable, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] ShareController {/api/shares}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares, GET} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/from-owner, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/metaData, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/complete, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/complete, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/isShareIdAvailable/:id, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:id/token, POST} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] FileController {/api/shares/:shareId/files}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files/zip, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files/:fileId, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/shares/:shareId/files/:fileId, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] ReverseShareController {/api/reverseShares}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/reverseShares, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/reverseShares/:reverseShareToken, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/reverseShares, GET} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/reverseShares/:reverseShareId, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] ConfigController {/api/configs}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/configs, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/:category, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/configs/admin, PATCH} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/testEmail, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/configs/admin/logo, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] UserController {/api/users}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users/me, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users/me, PATCH} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users/me, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users, GET} route +1ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users/:id, PATCH} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/users/:id, DELETE} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RoutesResolver] OAuthController {/api/oauth}: +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/oauth/available, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/oauth/status, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/oauth/auth/:provider, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/oauth/callback/:provider, GET} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [RouterExplorer] Mapped {/api/oauth/unlink/:provider, POST} route +0ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:48 PM     LOG [NestApplication] Nest application successfully started +18ms
pingvin  | [Nest] 33  - 01/01/2024, 12:16:53 PM     LOG [ClamScanService] ClamAV is not active
pingvin  | [Nest] 33  - 01/01/2024, 12:36:05 PM   ERROR [ExpressAdapter] Premature close
pingvin  | Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
pingvin  |     at ServerResponse.onclose (node:internal/streams/end-of-stream:159:30)
pingvin  |     at ServerResponse.emit (node:events:526:35)
pingvin  |     at emitCloseNT (node:_http_server:1023:10)
pingvin  |     at Socket.onServerResponseClose (node:_http_server:278:5)
pingvin  |     at Socket.emit (node:events:526:35)
pingvin  |     at TCP.<anonymous> (node:net:337:12)
```

## Config
```yml
version: '3.8'
services:
  pingvin-share:
    container_name: pingvin
    image: stonith404/pingvin-share:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "./pingvin-data:/opt/app/backend/data"
      - "./pingvin-data/images:/opt/app/frontend/public/img"
```

### 🌐 Browser

Firefox

**Comment by stonith404** [comment] 2024-01-02 16:32
Probably related to #354. The issue is strangely only with Firefox. I'll close this issue as this is a duplicate. Feel free to participate in the discussion in the other issue.

**Closed by stonith404** 2024-01-02 16:32 UTC
Labels: bug

**Comment by stonith404** [comment] 2024-01-02 20:17
Sorry I overlooked the part of the upload speed. Feel free to create a bug report for that too. The issue might be that the file gets uploaded in small parts, maybe I can improve this algorithm.
