### ISSUE TITLE
🐛 Bug Report: Share isn't working

### ISSUE THREAD

**Issue by krintek** [stonith404/pingvin-share#113] opened 2023-03-05 02:31 UTC
### 👟 Reproduction steps

when I tried to share anything the share option isn't working in the latest version.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/87629857/222938326-032214ae-e7bd-42b9-af19-03c011d3078d.png">

VERSION: 0.11.0

### 👍 Expected behavior

File-sharing.

### 👎 Actual Behavior

It actually doesn't do anything.

### 🌐 Browser

Brave Browser

**Comment by jeffxt** [comment] 2023-03-05 02:37
Same here while using Firefox.  There is no progress indicator for the file upload, and pressing the Share button does nothing.

**Comment by Hukuma1** [comment] 2023-03-05 04:41
Seeing the same thing. Console shows:

```
Uncaught Error: Config variable ENABLE_SHARE_EMAIL_RECIPIENTS not found
```

I do not have this feature enabled. Also seeing a 404 on `favicon.ico` (even though it's in /img/ folder). And `icon-144x144.png` is also 404. It's inside img/icons/icon-144x144x.png)

**Comment by stonith404** [comment] 2023-03-05 09:53
That's critical, thanks for your report! It should be fixed in `v0.11.1`.

**Comment by stonith404** [comment] 2023-03-05 09:55
> Also seeing a 404 on `favicon.ico` (even though it's in /img/ folder). And `icon-144x144.png` is also 404. It's inside img/icons/icon-144x144x.png)


Does someone else have the same issue as @Hukuma1, because I can't reproduce it?

**Comment by Hukuma1** [comment] 2023-03-05 16:21
> > Also seeing a 404 on `favicon.ico` (even though it's in /img/ folder). And `icon-144x144.png` is also 404. It's inside img/icons/icon-144x144x.png)
> 
> Does someone else have the same issue as @Hukuma1, because I can't reproduce it?

`v0.11.1` fixed it apparently. Thank you!

**Closed** 2023-03-06 07:18 UTC
Labels: bug
