### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by gabeanelson** [stonith404/pingvin-share#31] opened 2022-12-08 18:29 UTC
For Pingvin Share, the email notification only seems to work with GMail's SMTP service. Would it be possible to get compatibility with SendGrid. Currently you request the smtp host, smtp email, smtp password, and smtp port. For SendGrid to work, there also needs to be a spot for the smtp username, which can be different than the smtp email.

**Comment by stonith404** [comment] 2022-12-08 22:26
Added to the new release v0.3.3 :) Feel free to reopen the issue if something doesn't work.

**Comment by gabeanelson** [comment] 2022-12-08 23:47
Thanks for the super fast turnaround!! I set up the SendGrid SMTP service, and it works great. Though after making this change, I created a new share with email recipients, and the link that was included in the email didn't work. When I clicked on the link, it said:
 "Not found  
This share can't be found. Please check the link."

**Comment by stonith404** [comment] 2022-12-09 06:49
Could you try it again? Maybe the share has expired. If it doesn't work could you share how the link looks like?

**Comment by gabeanelson** [comment] 2022-12-09 15:32
Below is the link to the share that I made with an email recipient (I removed my Domain name/TLD with Xs):

https://ping.XXXX.XXX/share/QyMjk0N

Below is the message that I received via email (I removed my Domain name/TLD with Xs):

Hey!
gabeanelson shared some files with you. View or dowload the files with this link: http://url6296.XXXX.XXX/ls/click?upn=NmzolZjweMivK9EztefjncLaSsiZ6nDxKFVEMpn6ozl6-2F5Du-2BR9f-2FvpVPG9d3l8F1WL0KULJ5COMtsbwzWpdzA-3D-3DsYhS_JGSDFTwtOzx5MSExQgcsvEfD2vl70aEF8w0-2FWOn8I6rObNqmp2tehhR7VI7Bw9Ie0Ws3R5SnMQkIlIbr-2BRBx28f5bPhx2KglOLGDsYqIFRk8D7Anhfo-2F1Edqjl2h4p9SBNxF4kkvhM7IVRmN143JKscykUs-2Ba6MdA-2FZ9WKn-2F6I3e5a7TGAButn0xwNkC6nCxOF3LIyoxelg7nEDwo5U8Kw-3D-3D
Shared securely with Pingvin Share 🐧

As you can see, it changes the Subdomain from https://ping to http://url6296.

That said, I also went back and changed the STMP settings back to GMail, and after going back to the GMail STMP settings, the link I received via email was the same as the one shown when I initially created the share and it worked great.

**Comment by stonith404** [comment] 2022-12-09 15:42
Probaly Send Grid changes the url because in the code the url has the following pattern: http://APP_URL/share/SHARE_ID.

I would google a bit about this issue because if it works with Gmail but not with Sendgrid it can't be an issue with Pingvin Share.

**Comment by scubeedu2** [comment] 2022-12-09 20:35
Also trying to use with my Gmail account which uses 2FA.  I have the app key generated as the password, but goes nowhere.

**Comment by stonith404** [comment] 2022-12-09 21:30
> Also trying to use with my Gmail account which uses 2FA.  I have the app key generated as the password, but goes nowhere.

Do you get an error or does the share get created successfully? Also did you checked the spam folder?

**Comment by scubeedu2** [comment] 2022-12-09 21:35
> > Also trying to use with my Gmail account which uses 2FA.  I have the app key generated as the password, but goes nowhere.
> 
> Do you get an error or does the share get created successfully? Also did you checked the spam folder?

No error codes, share was created fine, and did not appear in the spam folder.  Tried sending to other email accounts which did not work either.

**Comment by stonith404** [comment] 2022-12-09 22:24
Do you see anything in the logs? You can see the logs with `docker compose logs pingvin-share`

**Comment by scubeedu2** [comment] 2022-12-09 23:52
> @scubeedu2, in the configuration section, did you add your GMail address as the SMTP_USERNAME also?

Yes, all filled in and on port 465.

**Comment by scubeedu2** [comment] 2022-12-09 23:55
> Do you see anything in the logs? You can see the logs with `docker compose logs pingvin-share`

I'm running this as a stack in Portainer, and the log for this shows no errors at all.

**Comment by scubeedu2** [comment] 2022-12-10 01:59
> Can you confirm that sending emails works on this website: https://www.smtper.net

Yes, this works, however I did have to change to port 587 with SSL option selected.  I updated my Pingvin config to port 587 but it still does not work.  There is no option to select SSL option if that matters?

**Comment by stonith404** [comment] 2022-12-10 09:58
Maybe SSL is the issue. On the website I've sent you, does sending emails work on port 587 when SSL is disabled?

**Comment by scubeedu2** [comment] 2022-12-10 15:00
> Maybe SSL is the issue. On the website I've sent you, does sending emails work on port 587 when SSL is disabled?

No it doesn't.  Here is the message given on smtper.net with SSL disabled:

SMTP send error
The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.0 Must issue a STARTTLS command first.

**Comment by stonith404** [comment] 2022-12-10 16:30
I added the config variable `SMTP_SSL`, could your try again with the development image of Pingvin Share `stonith404/pingvin-share:development` and please let me know if it works.

**Comment by scubeedu2** [comment] 2022-12-10 16:57
> I added the config variable `SMTP_SSL`, could your try again with the development image of Pingvin Share `stonith404/pingvin-share:development` and please let me know if it works.

No, sorry it still does not work.  I also tried it with FF and it did not work in that browser either.  Here's a pic of my config just FYI.

![Pingvin Config](https://user-images.githubusercontent.com/107091598/206866306-de345291-be95-464e-a1b7-2b46ec854a95.JPG)

**Comment by stonith404** [comment] 2022-12-10 17:20
Strange... Under the hood pingvin share uses nodemailer. If you have node installed, could you try to run this script and see if it works?
```js
const nodemailer = require("nodemailer");

// async..await is not allowed in global scope, must use a wrapper
async function main() {

  // create reusable transporter object using the default SMTP transport
  let transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false, // use ssl?
    auth: {
      user: "you@gmail.com",
      pass: "your password", 
    },
  });

  // send mail with defined transport object
  let info = await transporter.sendMail({
    from: 'you@gmail.com', // sender address
    to: "you@gmail.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world?", // plain text body
    html: "<b>Hello world?</b>", // html body
  });

  console.log("Message sent: %s", info.messageId);
  // Message sent: <b658f8ca-6296-ccf4-8306-87d57a0b4321@example.com>
}

main().catch(console.error);
```
Example is taken from the official nodemailer site: https://nodemailer.com/about/#example

**Comment by stonith404** [comment] 2022-12-10 17:42
I've just tested it with gmail smtp and it works for me. Sorry but I can't help you here further, because it really can't be an issue on Pingvin Shares side. I would try another recipient email or check your spam.
It worked for me with this config:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/58886915/206868150-8c3a3337-7f4f-4ea9-974c-355a568e213b.png">

**Comment by scubeedu2** [comment] 2022-12-10 17:58
> I've just tested it with gmail smtp and it works for me. Sorry but I can't help you here further, because it really can't be an issue on Pingvin Shares side. I would try another recipient email or check your spam. It worked for me with this config: <img alt="image" width="923" src="https://user-images.githubusercontent.com/58886915/206868150-8c3a3337-7f4f-4ea9-974c-355a568e213b.png">

Are you also using 2FA with your gmail account which requires that you use an app password?

**Comment by stonith404** [comment] 2022-12-10 18:13
Yes exactly. I also noticed, that it doesn't matter if you use the port 465 or 587. But the email must be sent by Pingvin Share because if anything goes wrong, Pingvin Share will show an error that says your share couldn't be created...

**Comment by amnesiacsardine** [comment] 2022-12-14 15:05
> > I've just tested it with gmail smtp and it works for me. Sorry but I can't help you here further, because it really can't be an issue on Pingvin Shares side. I would try another recipient email or check your spam. It worked for me with this config: <img alt="image" width="923" src="https://user-images.githubusercontent.com/58886915/206868150-8c3a3337-7f4f-4ea9-974c-355a568e213b.png">
> 
> Are you also using 2FA with your gmail account which requires that you use an app password?

Normally I think you're supposed to leave out @gmail.com for the SMTP username. Worth a try anyway.

**Comment by vawaver** [comment] 2023-01-04 10:13
Hi,
I can confirm that sending emails does not work for me as well.
I tried 2 different email accounts (no Gmail) that I normally use for other services and they work 100%. No 2FA used.
465, 25, and 587 ports were tried but with the same error.
I tried a Gmail account too as 3rd option but it does not work too.

My docker was created via Portainer -> Stack.
Docker image version from 2022-12-30 14:46:52

I am sending a log export from docker.
It seems to me that Pingvin cannot use 465 port.

[_pingvin-pingvin-share-1_logs.txt](https://github.com/stonith404/pingvin-share/files/10343091/_pingvin-pingvin-share-1_logs.txt)

Waiting for your reply.

**Comment by stonith404** [comment] 2023-01-04 11:03
@vawaver Can you share the value of the smtp host you've entered?

**Comment by vawaver** [comment] 2023-01-04 11:54
> @vawaver Can you share the value of the smtp host you've entered?

1. smtp.wy.sk
2. mail.krajcikovci.sk
3. smtp.gmail.com

**Comment by stonith404** [comment] 2023-01-04 14:40
@vawaver I looked into it and I noticed that the the settings are only applied after a restart of the docker container. I just fixed it (11174656e425c4be60e4f7b1ea8463678e5c60d2) but as a work around, until I release the fix, you have to restart the docker container. Let me know if it works.

**Comment by vawaver** [comment] 2023-01-05 06:31
Hello,
I recreate the new container to the latest version but Pingvin did not start.
There is some issue with migration.
Check the logs - sending them as an attachment.


[_pingvin-pingvin-share-1_logs.txt](https://github.com/stonith404/pingvin-share/files/10349853/_pingvin-pingvin-share-1_logs.txt)

**Comment by vawaver** [comment] 2023-01-05 09:29
> @vawaver Yep I messed up something, please see this [#73 (comment)](https://github.com/stonith404/pingvin-share/issues/73#issuecomment-1371897205) to fix the issue.

Hello,
I use your suggestion but I like to add something to your tutorial.

Let me share it.

1. **Remove pingvin docker container** - just stopping does not help
2. Install Sqlite first, with apt: `sudo apt install sqlite`
3. Cd into the root directory of Pingvin Share

```
sudo sqlite3 data/pingvin-share.db "DELETE FROM _prisma_migrations WHERE migration_name = '20230104145733_v0_5_1'; drop table new_RefreshToken;"
docker compose pull or Portainer users can redeploy Pingvin Stack
docker compose up -d 
```
I set up an Email block with my SMTP settings (port 465) and now it works. No need to restart Pingvin docker.

**Comment by stonith404** [comment] 2023-01-05 09:33
@vawaver Nice! `docker compose down` should delete the container, what did you make to remove the docker container?

**Comment by vawaver** [comment] 2023-01-05 09:42
> @vawaver Nice! `docker compose down` should delete the container, what did you make to remove the docker container?

I am lazy so I use Portainer. It is easy to remove it.  2-clicks and done.
Advanced users can use the docker commands.

```
docker ps
docker stop pingvin-containerID
docker rm pingvin-containerID
```

**Comment by stonith404** [comment] 2023-01-05 10:06
@vawaver Ah ok [docker compose down](https://docs.docker.com/engine/reference/commandline/compose_down/) removes the containers too, so it should work. So you don't have any issues anymore with SMTP? If yes I'll close this issue because it contains a lot off topic comments.

**Comment by vawaver** [comment] 2023-01-05 10:09
@stonith404  you can close it. Everything works.

**Closed** 2023-01-05 10:13 UTC
Labels: invalid
