### ISSUE TITLE
🐛 Bug Report: Uncaught Error: Minified React error with HTTPS

### ISSUE THREAD

**Issue by pandamasta** [stonith404/pingvin-share#388] opened 2024-01-18 12:13 UTC
### 👟 Reproduction steps

I go through a reverse proxy (Nginx Proxy Manager) and forward to the backend on LXC container where Pingvin is.
I use a proxmox helper script https://tteck.github.io/Proxmox/
I'll do test on docker in the future too

All is fine if the reverse proxy is on HTTP only trough the backend in HTTP too.

The problem arise when I enable HTTPS on the reverse proxy I catch the following error in my browser debuger.

I'm not sure HTTPS introduce issue by itself as it just serve through SSL to HTTP backend

```
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-b1cc30c22480787c.js:1:17425](https://upload.dev.bitiso.net/_next/static/chunks/main-b1cc30c22480787c.js)
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

![image](https://github.com/stonith404/pingvin-share/assets/5476200/06b7726b-d4b9-4f89-aa0d-39bdb3c20e82)

### 👍 Expected behavior

Works like in HTTP

### 👎 Actual Behavior

On browser:

Application error: a client-side exception has occurred (see the browser console for more information).

### 🌐 Browser

Firefox

**Comment by stonith404** [comment] 2024-01-23 14:24
This is a duplicate of #362. Please participate in the discussion there.

**Closed by stonith404** 2024-01-23 14:24 UTC
Labels: bug
