### ISSUE TITLE
🚀 Feature: Make "Name" a universal thing

### ISSUE THREAD

**Issue by InvitedToHell** [stonith404/pingvin-share#459] opened 2024-04-28 18:05 UTC
### 🔖 Feature description

When you view your shares, the "Name" shows the share URL ID. 
![image](https://github.com/stonith404/pingvin-share/assets/73737531/fa1c10ff-70b7-421b-ab41-d4d60eb2e73d)

When I edit or upload a file, the name means the file name.
![image](https://github.com/stonith404/pingvin-share/assets/73737531/329d6b05-6a53-445b-b262-752856fa6768)

Shouldn't we be able to control the name of the share? I think right now, the description says what the share contains. But I think we should be able to name the share instead of describe it. 

### 🎤 Pitch

I think it would be easier and also more logical to be able to change the name of the share instead of describing what it contains. If I have a share with 3 files containing assets for my project, the thing I would want to see when I go through my shares is "assets-projectA" or smth. similar. I don't care what the ID of the URL is. If I want the URL, I can use the button to copy it. The name should be something recognizable.

**Comment by stonith404** [comment] 2024-05-03 21:30
This appears to be a duplicate of #430, correct? If so, it is currently awaiting release. :)

**Closed** 2024-05-04 07:14 UTC
Labels: feature
