### ISSUE TITLE
🐛 Bug Report: S3 shares are not deleted on S3 compatible buckets

### ISSUE THREAD

**Issue by GitNees** [stonith404/pingvin-share#705] opened 2024-12-24 08:20 UTC
### 👟 Reproduction steps

Trying to delete shares in sharemanagement, uploaded on S3

### 👍 Expected behavior

Share is deleted from bucket

### 👎 Actual Behavior

Website seems to remove share,  refresh share management, share is again visible, check bucket, share is still there,

additional info: my hosting says this about compatibility and API for S3 compatible buckets, perhaps something is missing? 
https://docs.hetzner.com/storage/object-storage/faq/buckets-objects

### 📜 Logs

pingvin-share-1  |     at S3FileService.deleteAllFiles (/opt/app/backend/dist/src/file/s3.service.js:177:19)
pingvin-share-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
pingvin-share-1  |     at async ShareService.remove (/opt/app/backend/dist/src/share/share.service.js:233:9)
pingvin-share-1  |     at async ShareController.remove (/opt/app/backend/dist/src/share/share.controller.js:69:9)
pingvin-share-1  | 2024-12-24 08:03:32.887248954 +0000 UTC m=+520.491887298 write error: can't make directories for new logfile: mkdir /var/log/caddy: permission denied
pingvin-share-1  | [Nest] 47  - 12/24/2024, 8:03:40 AM   ERROR [ExceptionsHandler] Could not delete all files from S3
pingvin-share-1  | Error: Could not delete all files from S3

**Comment by m-mattia-m** [comment] 2024-12-24 09:13
I will take a look at this issue in the next few days.

**Comment by stonith404** [comment] 2024-12-24 16:20
Thanks @m-mattia-m :)

**Comment by m-mattia-m** [comment] 2024-12-25 10:00
@GitNees, I can't reproduce this bug with my S3 provider (see attached video). Could you check if you have [object locking enabled (how-do-i-protect-my-objects-from-getting-deleted-by-accident)](https://docs.hetzner.com/storage/object-storage/faq/buckets-objects#how-do-i-protect-my-objects-from-getting-deleted-by-accident) (which doesn't allow you to delete files)? If not, could you please send me more information about what you are doing step-by-step?

![pingvin-share](https://github.com/user-attachments/assets/56b62f54-0b59-4b41-882f-58a5c0401933)

**Comment by GitNees** [comment] 2024-12-25 12:03
Bingo! I found the problem because of your video.
But this was confusing. 

When my bucket was created, my provider, it gives me a full url i can copy like "testbucket.ger1.mystorageexample.com"
as this included the bucketname also, and now learned that is not the endpoint URL, i did find it strange that in the bucket, I saw after an upload, a new folder was created with the same bucketname with in there the path folder. so like /testbucket/shares/ instead of /shares/.

 But isnt that strange that it worked then if i put a "full" url including the bucketname in the endpoint? shouldnt it have failed if the endpoint was filled in like that? Perhaps there is a way to improve this? For n00bs like me. A check before saving if the bucketname is part of the endpoint url.

**Comment by m-mattia-m** [comment] 2024-12-25 13:10
Glad to hear it works now and that my video helped you :)

I think you can't really check for the endpoint and see if it's included because different providers (or even self-hosted providers like MinIO) can generate their own FQDNs. So it may be that some providers (or your own chosen MinIO URL) require the bucket name in the FQDN. However, if you google for "<your provider> object storage/s3 endpoints/api" (choosing either "object storage" or "s3" and the same for "endpoint" or "api"), you will usually get a page describing the endpoints.

[See, for example, the Hetzner endpoints](https://docs.hetzner.com/storage/object-storage/overview/#available-endpoints) or [my chosen provider: Exoscale](https://community.exoscale.com/api/sos/).

I'm creating a merge request to describe this in more detail in the documentation.

**Comment by m-mattia-m** [comment] 2024-12-26 17:22
@stonith404 Could you please close this issue? :)

**Closed** 2024-12-27 04:38 UTC
Labels: bug
