### ISSUE TITLE
🚀 Feature: Create a config option to allow an admin to require "Password Protection" be used for any shares created

### ISSUE THREAD

**Issue by XStylus** [stonith404/pingvin-share#614] opened 2024-09-25 05:43 UTC
### 🔖 Feature description

I'd like to request that there be a way to require "Password Protection" be used for any shares created.

### 🎤 Pitch

I host pingvin for usage in a small company environment. Most of our team members who will be using this to create shares are not tech savvy nor security savvy, so I need to make things as simple as possible for them. That means preventing them from being able to make lazily insecure choices.

Therefore, I'd like to configure pingvin so that my users cannot create a share unless they have specified a password for it.

 Thank you!

**Comment by edbourque0** [comment] 2024-09-26 14:47
+1

**Comment by stonith404** [comment] 2024-12-03 14:37
This is a duplicate of #400. Feel free to participate in the discussion there.

**Closed by stonith404** 2024-12-03 14:37 UTC
Labels: feature
