### ISSUE TITLE
🐛 Bug Report: logo.png does not show, permissions error

### ISSUE THREAD

**Issue by jdtate101** [stonith404/pingvin-share#703] opened 2024-12-23 16:13 UTC
### 👟 Reproduction steps

Installed app on docker using docker-compose file, no adjustments, the main logo doe not show (shows as missing file). 

### 👍 Expected behavior

It should show up as expected. the logo.png is in the dir /opt/app/frontend/public/img/ with 0755 permissions.

### 👎 Actual Behavior

It shows errors in the log file as well as a general error for writing log files to /var/log/caddy.

When trying to replace with my own logo, it errors on upload and the missing file behaviour continues.

### 📜 Logs

2024-12-22 09:26:43.137175608 +0000 UTC m=+153.541258049 write error: can't make directories for new logfile: mkdir /var/log/caddy: permission denied
[Nest] 58  - 12/22/2024, 9:26:43 AM   ERROR [ExceptionsHandler] EACCES: permission denied, open '../frontend/public/img/logo.png'
Error: EACCES: permission denied, open '../frontend/public/img/logo.png'
    at Object.openSync (node:fs:573:18)
    at Object.writeFileSync (node:fs:2380:35)
    at LogoService.create (/opt/app/backend/dist/src/config/logo.service.js:17:12)
    at async ConfigController.uploadLogo (/opt/app/backend/dist/src/config/config.controller.js:47:16)
[Nest] 58  - 12/22/2024, 9:28:19 AM   ERROR [ExceptionsHandler] EACCES: permission denied, open '../frontend/public/img/logo.png'

**Comment by stonith404** [comment] 2024-12-23 20:14
Thanks for reporting this. Would you mind to checkout the `stonith404/pingvin-share:development` image and let me know if the issue is fixed?

**Comment by jdtate101** [comment] 2024-12-24 05:56
Yes...fixed in the development image.

**Comment by stonith404** [comment] 2024-12-24 16:20
This should be fixed in `v1.7.1`.

**Closed by stonith404** 2024-12-24 16:20 UTC
Labels: bug
