### ISSUE TITLE
🚀 Feature: Configurable ports and database through env

### ISSUE THREAD

**Issue by szlend** [stonith404/pingvin-share#144] opened 2023-04-17 17:19 UTC
### 🔖 Feature description

The ports and database url could be configurable through environmental variables. I think at minimum you would want:

Frontend:
- `PORT=3000`
- `API_URL=http://localhost:8080`

Backend:
- `PORT=8080`
- `DATABASE_URL=file:../data/pingvin-share.db?connection_limit=1`

Right now to make this packagable for NixOS I need to apply the following patches:

Backend:
```bash
substituteInPlace src/main.ts \
  --replace 'await app.listen(8080)' 'await app.listen(+process.env.PORT)'

substituteInPlace src/prisma/prisma.service.ts \
  --replace '"file:../data/pingvin-share.db?connection_limit=1"' 'process.env.DATABASE_URL'

substituteInPlace prisma/schema.prisma \
  --replace '"file:../data/pingvin-share.db"' 'env("DATABASE_URL")' 
```

Frontend:
```
substituteInPlace src/pages/_app.tsx \
  --replace '`http://localhost:8080' '`''${process.env.API_URL}'

substituteInPlace src/middleware.ts 'src/pages/api/[...all].tsx' \
  --replace '"http://localhost:8080' 'process.env.API_URL + "'
```

### 🎤 Pitch

Installing pingivin-share on a shared system (outside of containers, e.g. NixOS) is currently difficult because the ports are hardcoded and can easily clash with other applications. The database is also hardcoded to a path relative to prisma, which makes it impossible to ship the application into a non-writable prefix (e.g. `/nix/store` or `/usr`).

**Comment by stonith404** [comment] 2023-04-18 16:08
Good point. This shouldn't be much work but currently my laptop is in repair so it could take some time until I can implement this.

When you're finished I would love if you add the NixOS installation instructions to the README :)

**Comment by stonith404** [comment] 2023-04-24 06:46
I'm currently working on this. I think we don't need `API_URL` as we just could use `http://localhost:${FRONTEND_PORT}`. Do you think this is sufficient?

**Comment by stonith404** [comment] 2023-04-24 06:51
Do you start the frontend with `npm run start`? Because it isn't possible to specify the port in the code, only in the command like this: `npm run start -p $FRONTEND_PORT`. Would this approach work with your installation?

**Comment by szlend** [comment] 2023-04-24 09:22
Not strictly necessary, but I think it’s worth having the option, say you want to sandbox each service into its own network namespace. It’s a bit of a niche use-case, but it’s definitely something I’ve done in the past.On 24 Apr 2023, at 08:46, Elias Schneider ***@***.***> wrote:﻿
I'm currently working on this. I think we don't need API_URL as we just could use http://localhost:${FRONTEND_PORT}. Do you think this is sufficient?

**Comment by szlend** [comment] 2023-04-24 09:22
> I'm currently working on this. I think we don't need `API_URL` as we just could use `http://localhost:${FRONTEND_PORT}`. Do you think this is sufficient?

Not strictly necessary, but I think it’s worth having the option, say you want to sandbox each service into its own network namespace. It’s a bit of a niche use-case, but it’s definitely something I’ve done in the past.

**Comment by szlend** [comment] 2023-04-24 09:28
Can't verify right now but I think the fronted server already supports the 'PORT' env var.

**Comment by stonith404** [comment] 2023-04-24 12:10
Yes the frontend supports the `PORT` env variable. The backend port should have another env variable for the port as it would clash with the `PORT` env variable of the frontend. Or I'm wrong?
So as a summary I would add these variables:
- `PORT` - frontend port
- `BACKEND_PORT` - backend port
- `BACKEND_URL` - backend url
- `DATABASE_URL`- database url

Is this correct?

**Comment by stonith404** [comment] 2023-04-25 21:42
Added in e5071cba1204093197b72e18d024b484e72e360a. Let me know if this fits your needs :)

Backend
- `PORT`
- `DATABASE_URL`

Frontend
- `PORT`
- `API_URL`

**Comment by szlend** [comment] 2023-04-26 17:49
@stonith404 Thank you! Though I just tried the new version and it seems like the database path is still hardcoded in `schema.prisma`. In my setup I replaced `"file:../data/pingvin-share.db"` with `env("DATABASE_URL")`. It doesn't seem like it's possible to set a default unfortunately: https://github.com/prisma/prisma/issues/222

**Comment by szlend** [comment] 2023-04-26 21:17
Actually, I think it could be worked around by placing an `.env` file in the `prisma` directory, which could serve as a default for `DATABASE_URL`. I can't test right now, but from what I could gather, system env vars should still have precedence over the `.env` file. This is kinda janky though.

> do you think it matters where the database file is stored?

From what I remember, the database file is placed relative to the prisma schema directory. At least when running migrations using the prisma client). If you package the app into a non-writable system path, that's a problem yeah.

> Because the database file is stored inside the same folder as the uploads.

The uploads folder is actually relative to the working directory which is really easy to change. You just execute the server from whatever path you want as the root, by `cd`-ing into it. Though I guess this probably wouldn't work through `npm`.  Though ideally, you would be able to configure `UPLOAD_PATH` as well.

**Comment by stonith404** [comment] 2023-04-26 21:30
Great idea! Creating a `.env` file inside the prisma folder works and the system env variables will be prioritized. Although this isn't a really beautiful solution, this would be a valid workaround. What do you think?

**Comment by szlend** [comment] 2023-04-26 21:56
> Great idea! Creating a `.env` file inside the prisma folder works and the system env variables will be prioritized. Although this isn't a really beautiful solution, this would be a valid workaround. What do you think?

That's great! Yeah it's kinda janky but I think it's worth the cost.

What do you think about also making the upload dir configurable? Currently I symlink it to another drive, but it would be nice if I could just configure it as well.

**Comment by stonith404** [comment] 2023-04-27 11:42
I've just fixed the prisma issue and added an env variable that allows to specify the data directory. It isn't merged yet because it would be nice if you could check it out first if this works for you. The newest changes are in the [`configureable-database-url`](https://github.com/stonith404/pingvin-share/tree/configureable-database-url) branch.

Here are the added env variables again:
Backend
- `PORT`
- `DATABASE_URL`
- `DATA_DIRECTORY`

Frontend
- `PORT`
- `API_URL`

**Comment by szlend** [comment] 2023-04-28 15:43
Awesome, I tested the latest changes and everything seems to be working fine! Gonna try and package this for [nix](https://search.nixos.org/packages) when I get the chance.

**Comment by szlend** [comment] 2023-04-28 16:09
This part doesn't work for me:
```
await fetch(`${request.nextUrl.origin}/api/configs`)
```

```
Error [TypeError]: fetch failed
```
Shouldn't this just resolve to `API_URL`? It's executed on the server-side.

**Comment by stonith404** [comment] 2023-04-29 15:57
That's strange I can't reproduce this. The problem is we can't use the `getConfig()` function in a middleware so we have to use `request.nextUrl.origin` as a workaround. Would you mind to replace
```ts
const config = await (
      await fetch(`${request.nextUrl.origin}/api/configs`)
    ).json();
```
with 
```ts
  console.log(request.nextUrl);
  let config: any;
  try {
    // Get config from backend
    config = await (
      await fetch(`${request.nextUrl.origin}/api/configs`)
    ).json();
  } catch (e) {
    console.log(e);
  }
```
so we can get a better error message?

**Comment by szlend** [comment] 2023-04-30 14:44
Two issues:

- On the backend, the port needs to be cast into an integer: `await app.listen(+process.env.PORT)`
- On the frontend, the `next.config.js` file is evaluated at build time, not at runtime. So the apiURL will always be set to :8080

**Comment by stonith404** [comment] 2023-04-30 17:34
I fixed the casting.

Additionally I've debugged the error a bit and I found out that it it takes the runtime env variables with `npm run start` (`npx next start`) correctly. I really don't have a clue why this works but `node .next/standalone/server.js` not. Would it be possible that you use the `npx next start` command?

Sure it would be nice if the hoster can setup a reverse proxy by his own but it gets really complicated if I want to support the Docker version too. I think for the  most of the users it's fine to use the current implemented reverse proxy. Do you think this is enough for the moment?

**Comment by szlend** [comment] 2023-04-30 17:58
> Would it be possible that you use the npx next start command?
I would prefer avoiding packaging unnecessary dependencies. But yeah, I can debug this myself.

> Do you think this is enough for the moment?
Yeah, no worries.

Thanks!

**Comment by stonith404** [comment] 2023-05-01 20:44
Okay :) Let me know if you need anything

**Comment by stonith404** [comment] 2023-05-09 16:52
Added in `v0.15.0`. Feel free to create another issue, if you come across any other issues :)

**Closed by stonith404** 2023-05-09 16:52 UTC
Labels: feature
